name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: findafriendapi

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm dlx prisma generate

      - run: pnpm test:e2e
        env:
          JWT_SECRET: test
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/findafriendapi?schema=public"